import { AIModelConfig, AgentId } from '../types';

export interface DetailedAIModel extends AIModelConfig {
  contextWindow?: string;
  latency?: string;
  architecture?: string;
  providerLabel: string;
  description: string;
}

export const ALL_SUPPORTED_MODELS: DetailedAIModel[] = [
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    role: 'Orchestrator',
    agentId: 'orchestrator',
    badge: 'Orchestrator',
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.45)',
    actionText: 'Planning • Coordinating agents',
    statusBadgeText: 'Task Decomposed • 4 subtasks created',
    contextWindow: '2,000,000 tokens',
    latency: '~420ms',
    architecture: 'Multimodal MoE',
    providerLabel: 'Google Antigravity Native',
    description: 'Ultra-long context window ideal for orchestrating complex codebases without external API keys.',
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    role: 'Research Agent',
    agentId: 'research',
    badge: 'Fast Reasoning',
    color: '#60a5fa',
    glowColor: 'rgba(96, 165, 250, 0.45)',
    actionText: 'Ultra-fast semantic search & synthesis',
    statusBadgeText: 'Rapid Ingestion',
    contextWindow: '1,000,000 tokens',
    latency: '~180ms',
    architecture: 'Distilled Multimodal',
    providerLabel: 'Google Antigravity Native',
    description: 'Sub-200ms latency model for immediate file verification and live parsing.',
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    role: 'Design Agent',
    agentId: 'design',
    badge: 'Design & UX',
    color: '#fb923c',
    glowColor: 'rgba(251, 146, 60, 0.45)',
    actionText: 'UI/UX Analysis • Designing new layout...',
    statusBadgeText: 'Wireframe & Token Audit',
    contextWindow: '200,000 tokens',
    latency: '~650ms',
    architecture: 'Dense Transformer',
    providerLabel: 'Anthropic',
    description: 'State-of-the-art visual and design reasoning with nuanced frontend token awareness.',
  },
  {
    id: 'claude-3.5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'anthropic',
    role: 'Test / Review Agent',
    agentId: 'tester',
    badge: 'Fast Review',
    color: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    actionText: 'Lint & Regression Unit Check',
    statusBadgeText: 'Snappy Verification',
    contextWindow: '200,000 tokens',
    latency: '~210ms',
    architecture: 'Compact Dense',
    providerLabel: 'Anthropic',
    description: 'Blazing fast test runner with exceptional code safety and syntax validation.',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    role: 'Coder Agent',
    agentId: 'coder',
    badge: 'Backend & Code',
    color: '#34d399',
    glowColor: 'rgba(52, 211, 153, 0.45)',
    actionText: 'Implementing Features • Editing 6 files...',
    statusBadgeText: 'Active Refactoring Pass',
    contextWindow: '128,000 tokens',
    latency: '~520ms',
    architecture: 'Omni-Transformer',
    providerLabel: 'OpenAI',
    description: 'Comprehensive code generation, AST transformations, and multi-file refactoring engine.',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    role: 'Research Agent',
    agentId: 'research',
    badge: 'Lightweight Code',
    color: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    actionText: 'Dependency & API Check',
    statusBadgeText: 'Rapid Scan',
    contextWindow: '128,000 tokens',
    latency: '~240ms',
    architecture: 'Dense Transformer',
    providerLabel: 'OpenAI',
    description: 'Cost-effective high-throughput model for auxiliary documentation and dependency queries.',
  },
  {
    id: 'perplexity-sonar',
    name: 'Perplexity Sonar',
    provider: 'perplexity',
    role: 'Research Agent',
    agentId: 'research',
    badge: 'Research',
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.4)',
    actionText: 'Researching best practices • Found 12 relevant sources',
    statusBadgeText: 'Deep Benchmark Scan',
    contextWindow: '128,000 tokens',
    latency: '~480ms',
    architecture: 'Online Search Augmentation',
    providerLabel: 'Perplexity AI',
    description: 'Live real-time citation retrieval and up-to-date framework documentation cross-referencing.',
  },
  {
    id: 'llama-3.1-70b',
    name: 'Llama 3.1 70B',
    provider: 'meta',
    role: 'Test / Review Agent',
    agentId: 'tester',
    badge: 'Testing & Review',
    color: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.45)',
    actionText: 'Test suite in progress • 14/37 tests passed',
    statusBadgeText: 'WCAG AAA & Regression Guard',
    contextWindow: '128,000 tokens',
    latency: '~580ms',
    architecture: 'Open Weights Llama 3',
    providerLabel: 'Meta AI / Local',
    description: 'Excellence in rigorous deterministic evaluation, boundary testing, and adversarial fuzzing.',
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'meta',
    role: 'Orchestrator',
    agentId: 'orchestrator',
    badge: 'Open Orchestrator',
    color: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.45)',
    actionText: 'Autonomous Step Dispatcher',
    statusBadgeText: 'DAG Resolution',
    contextWindow: '128,000 tokens',
    latency: '~540ms',
    architecture: 'Grouped-Query Attention',
    providerLabel: 'Meta AI / Local',
    description: 'Flagship open model with frontier reasoning capabilities for mission graph management.',
  },
  {
    id: 'ollama-deepseek',
    name: 'DeepSeek R1 (Local)',
    provider: 'local',
    role: 'Coder Agent',
    agentId: 'coder',
    badge: 'Local Reasoning',
    color: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.4)',
    actionText: 'Offline Local Inference via Ollama',
    statusBadgeText: 'Zero-API-Key Local',
    contextWindow: '64,000 tokens',
    latency: '~680ms',
    architecture: 'DeepSeek Sparse MoE',
    providerLabel: 'Local Offline Engine',
    description: 'Open-weights reasoning powerhouse running fully locally with 0 telemetry or external keys.',
  },
  {
    id: 'qwen-2.5-coder',
    name: 'Qwen 2.5 Coder 32B',
    provider: 'local',
    role: 'Coder Agent',
    agentId: 'coder',
    badge: 'Local Coder',
    color: '#14b8a6',
    glowColor: 'rgba(20, 184, 166, 0.4)',
    actionText: 'Local Code Synthesis Pass',
    statusBadgeText: 'Offline Guard',
    contextWindow: '128,000 tokens',
    latency: '~380ms',
    architecture: 'RoPE Attention',
    providerLabel: 'Local Offline Engine',
    description: 'Specialized coding model tailored for multi-language syntax correctness and safe diffs.',
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large 2',
    provider: 'mistral',
    role: 'Design Agent',
    agentId: 'design',
    badge: 'Logic & Code',
    color: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    actionText: 'Synthesizing module AST...',
    statusBadgeText: 'Standby',
    contextWindow: '128,000 tokens',
    latency: '~440ms',
    architecture: 'European Frontier MoE',
    providerLabel: 'Mistral AI',
    description: 'High-precision European AI model specialized in deterministic reasoning and clean architecture.',
  },
];

export const AVAILABLE_MODELS: AIModelConfig[] = ALL_SUPPORTED_MODELS.slice(0, 5);

export type ModelTopologyMode = 'multi-provider' | 'all-gemini' | 'all-claude' | 'all-local' | 'custom';

export interface TopologyPreset {
  name: string;
  tag: string;
  badge: string;
  description: string;
  assignments: Record<AgentId, string>;
}

export const TOPOLOGY_PRESETS: Record<ModelTopologyMode, TopologyPreset> = {
  'multi-provider': {
    name: 'Multi-Model Swarm (Different Providers)',
    tag: 'Different Providers',
    badge: 'Cross-Ecosystem',
    description: 'Gemini 1.5 Pro (Orchestrator) + Claude 3.5 Sonnet (Design) + GPT-4o (Coder) + Perplexity Sonar (Research) + Llama 3.1 70B (Tester)',
    assignments: {
      orchestrator: 'gemini-1.5-pro',
      design: 'claude-3.5-sonnet',
      coder: 'gpt-4o',
      research: 'perplexity-sonar',
      tester: 'llama-3.1-70b',
    },
  },
  'all-gemini': {
    name: 'Unified Gemini Swarm (Same Model / Provider)',
    tag: 'Same Model (Gemini)',
    badge: 'Antigravity Native',
    description: '100% Google Gemini 1.5 Pro across all agents using your active Antigravity subscription without any external API keys',
    assignments: {
      orchestrator: 'gemini-1.5-pro',
      design: 'gemini-1.5-pro',
      coder: 'gemini-1.5-pro',
      research: 'gemini-1.5-flash',
      tester: 'gemini-1.5-pro',
    },
  },
  'all-local': {
    name: 'Local Offline Swarm (Open Weights / Privacy)',
    tag: 'All Local (Ollama)',
    badge: 'Offline Airgapped',
    description: 'Zero external cloud requests: DeepSeek R1, Qwen 2.5 Coder, and Llama 3.1 running locally through Ollama / Antigravity Local',
    assignments: {
      orchestrator: 'llama-3.3-70b',
      design: 'llama-3.1-70b',
      coder: 'ollama-deepseek',
      research: 'qwen-2.5-coder',
      tester: 'llama-3.1-70b',
    },
  },
  'all-claude': {
    name: 'Unified Claude Swarm (Same Model / Provider)',
    tag: 'Same Model (Claude)',
    badge: 'Anthropic Swarm',
    description: 'Claude 3.5 Sonnet & Haiku across all 5 roles for state-of-the-art vision, reasoning, and code quality',
    assignments: {
      orchestrator: 'claude-3.5-sonnet',
      design: 'claude-3.5-sonnet',
      coder: 'claude-3.5-sonnet',
      research: 'claude-3.5-sonnet',
      tester: 'claude-3.5-haiku',
    },
  },
  'custom': {
    name: 'Custom Multi-Model Matrix',
    tag: 'Custom Matrix',
    badge: 'User Configured',
    description: 'Individually tailor each role to any supported model or provider for your specific requirements',
    assignments: {
      orchestrator: 'gemini-1.5-pro',
      design: 'claude-3.5-sonnet',
      coder: 'ollama-deepseek',
      research: 'perplexity-sonar',
      tester: 'llama-3.1-70b',
    },
  },
};
